### ISSUE TITLE
Moa sync job

### ISSUE THREAD

**Issue by AshleyLu** [mfiers/Moa#18]
This problem is related to a moa sync job. What does it really mean by  'Namespace' object has no attribute 'recursive' ?

Moa: loaded sync actor simpleRunner
ERROR!
Unexpected error
Moa: Copying HA12 to UGC32
Warning: Encountered a run error?
Traceback (most recent call last):
  File "/usr/bin/moa", line 9, in <module>
    load_entry_point('moa==0.11.13', 'console_scripts', 'moa')()
  File "/usr/lib/python2.6/site-packages/moa/cli/main.py", line 226, in dispatch
    run_1()
  File "/usr/lib/python2.6/site-packages/moa/cli/main.py", line 170, in run_1
    run_2()
  File "/usr/lib/python2.6/site-packages/moa/cli/main.py", line 140, in run_2
    run_3(wd)
  File "/usr/lib/python2.6/site-packages/moa/cli/main.py", line 107, in run_3
    commandFunction(job, args)
  File "/usr/lib/python2.6/site-packages/moa/plugin/system/moautil.py", line 210, in cp
    if not args.recursive:
AttributeError: 'Namespace' object has no attribute 'recursive'

**Comment by AshleyLu** [comment]
oa: Copying /workspace/genome_analysis/bacterial/Pseudomonas/syringae/11.rmdup/SBV5 to HA12
ERROR!
Unexpected error
Warning: Encountered a run error?
Traceback (most recent call last):
  File "/usr/bin/moa", line 9, in <module>
    load_entry_point('moa==0.11.13', 'console_scripts', 'moa')()
  File "/usr/lib/python2.6/site-packages/moa/cli/main.py", line 226, in dispatch
    run_1()
  File "/usr/lib/python2.6/site-packages/moa/cli/main.py", line 170, in run_1
    run_2()
  File "/usr/lib/python2.6/site-packages/moa/cli/main.py", line 140, in run_2
    run_3(wd)
  File "/usr/lib/python2.6/site-packages/moa/cli/main.py", line 107, in run_3
    commandFunction(job, args)
  File "/usr/lib/python2.6/site-packages/moa/plugin/system/moautil.py", line 210, in cp
    if not args.recursive:
AttributeError: 'Namespace' object has no attribute 'recursive'

**Comment by mfiers** [comment]
Woops - that was my fault - I removed some code for recursive running - but forgot to leave it in place for moa cp - restored it - I'll ask eric for an update.
